DevOps-finalproject/status-page/statuspage/incidents/urls.py
from django.urls import path

from statuspage.views.generic import ObjectChangeLogView
from . import views
from .models import Incident, IncidentUpdate

app_name = 'incidents'
urlpatterns = [
    path('', views.IncidentListView.as_view(), name='incident_list'),
    path('add/', views.IncidentEditView.as_view(), name='incident_add'),
    path('edit/', views.IncidentBulkEditView.as_view(), name='incident_bulk_edit'),
    path('delete/', views.IncidentBulkDeleteView.as_view(), name='incident_bulk_delete'),
    path('<int:pk>/', views.IncidentView.as_view(), name='incident'),
    path('<int:pk>/edit/', views.IncidentEditView.as_view(), name='incident_edit'),
    path('<int:pk>/delete/', views.IncidentDeleteView.as_view(), name='incident_delete'),
    path('<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='incident_changelog', kwargs={
        'model': Incident,
    }),

    path('update/edit/', views.IncidentUpdateBulkEditView.as_view(), name='incidentupdate_bulk_edit'),
    path('update/delete/', views.IncidentUpdateBulkDeleteView.as_view(), name='incidentupdate_bulk_delete'),
    path('update/<int:pk>/', views.IncidentUpdateView.as_view(), name='incidentupdate'),
    path('update/<int:pk>/edit/', views.IncidentUpdateEditView.as_view(), name='incidentupdate_edit'),
    path('update/<int:pk>/delete/', views.IncidentUpdateDeleteView.as_view(), name='incidentupdate_delete'),
    path('update/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='incidentupdate_changelog', kwargs={
        'model': IncidentUpdate,
    }),

    path('past/', views.PastIncidentListView.as_view(), name='past'),
]

DevOps-finalproject/status-page/statuspage/maintenances/urls.py
from django.urls import path

from statuspage.views.generic import ObjectChangeLogView
from . import views
from .models import Maintenance, MaintenanceUpdate

app_name = 'maintenances'
urlpatterns = [
    path('', views.MaintenanceListView.as_view(), name='maintenance_list'),
    path('add/', views.MaintenanceEditView.as_view(), name='maintenance_add'),
    path('edit/', views.MaintenanceBulkEditView.as_view(), name='maintenance_bulk_edit'),
    path('delete/', views.MaintenanceBulkDeleteView.as_view(), name='maintenance_bulk_delete'),
    path('<int:pk>/', views.MaintenanceView.as_view(), name='maintenance'),
    path('<int:pk>/edit/', views.MaintenanceEditView.as_view(), name='maintenance_edit'),
    path('<int:pk>/delete/', views.MaintenanceDeleteView.as_view(), name='maintenance_delete'),
    path('<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='maintenance_changelog', kwargs={
        'model': Maintenance,
    }),

    path('update/edit/', views.MaintenanceUpdateBulkEditView.as_view(), name='maintenanceupdate_bulk_edit'),
    path('update/delete/', views.MaintenanceUpdateBulkDeleteView.as_view(), name='maintenanceupdate_bulk_delete'),
    path('update/<int:pk>/', views.MaintenanceUpdateView.as_view(), name='maintenanceupdate'),
    path('update/<int:pk>/edit/', views.MaintenanceUpdateEditView.as_view(), name='maintenanceupdate_edit'),
    path('update/<int:pk>/delete/', views.MaintenanceUpdateDeleteView.as_view(), name='maintenanceupdate_delete'),
    path('update/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='maintenanceupdate_changelog', kwargs={
        'model': MaintenanceUpdate,
    }),

    path('past/', views.PastMaintenanceListView.as_view(), name='past'),
]

DevOps-finalproject/status-page/statuspage/statuspage/urls.py
from django.conf import settings
from django.views.static import serve

from extras.plugins.urls import plugin_patterns, plugin_api_patterns, plugin_admin_patterns
from .admin import admin_site
from django.urls import path, include, re_path
from statuspage.views import HomeView, DashboardHomeView, SubscriberVerifyView, SubscriberManageView, \
    SubscriberUnsubscribeView, SubscriberSubscribeView, SubscriberRequestManagementKeyView
from users.views import LoginView, LogoutView
from statuspage.api.views import APIRootView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

openapi_info = openapi.Info(
    title="Status-Page API",
    default_version='v1',
    description="API to access Status-Page",
    terms_of_service="https://github.com/status-page/status-page",
    license=openapi.License(name="Apache 2.0 License"),
)

schema_view = get_schema_view(
    openapi_info,
    validators=['flex', 'ssv'],
    public=True,
    permission_classes=()
)

_patterns = [
    # Base Views
    path('', HomeView.as_view(), name='home'),

    path('subscribers/subscribe', SubscriberSubscribeView.as_view(), name='subscriber_subscribe'),
    path('subscribers/reqeust-management-key', SubscriberRequestManagementKeyView.as_view(), name='subscriber_management_key'),
    path('subscribers/<str:management_key>/verify', SubscriberVerifyView.as_view(), name='subscriber_verify'),
    path('subscribers/<str:management_key>/manage', SubscriberManageView.as_view(), name='subscriber_manage'),
    path('subscribers/<str:management_key>/unsubscribe', SubscriberUnsubscribeView.as_view(), name='subscriber_unsubscribe'),

    path('dashboard/', DashboardHomeView.as_view(), name='dashboard'),
    path('dashboard/login/', LoginView.as_view(), name='login'),
    path('dashboard/logout/', LogoutView.as_view(), name='logout'),

    # Apps
    path('dashboard/components/', include('components.urls')),
    path('dashboard/extras/', include('extras.urls')),
    path('dashboard/incidents/', include('incidents.urls')),
    path('dashboard/maintenances/', include('maintenances.urls')),
    path('dashboard/metrics/', include('metrics.urls')),
    path('dashboard/subscribers/', include('subscribers.urls')),
    path('dashboard/user/', include('users.urls')),

    # API
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/components/', include('components.api.urls')),
    path('api/extras/', include('extras.api.urls')),
    path('api/incidents/', include('incidents.api.urls')),
    path('api/maintenances/', include('maintenances.api.urls')),
    path('api/metrics/', include('metrics.api.urls')),
    path('api/subscribers/', include('subscribers.api.urls')),
    path('api/users/', include('users.api.urls')),
    path('api/docs/', schema_view.with_ui('swagger', cache_timeout=86400), name='api_docs'),
    path('api/redoc/', schema_view.with_ui('redoc', cache_timeout=86400), name='api_redocs'),
    re_path(r'^api/swagger(?P<format>.json|.yaml)$', schema_view.without_ui(cache_timeout=86400),
            name='schema_swagger'),

    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),

    # Plugins
    path('plugins/', include((plugin_patterns, 'plugins'))),
    path('api/plugins/', include((plugin_api_patterns, 'plugins-api'))),

    # Admin
    path('admin/background-tasks/', include('django_rq.urls')),
    path('admin/plugins/', include(plugin_admin_patterns)),
    path('admin/', admin_site.urls),

    path('__reload__/', include('django_browser_reload.urls')),
]

# Prepend BASE_PATH
urlpatterns = [
    path('{}'.format(settings.BASE_PATH), include(_patterns))
]

DevOps-finalproject/status-page/statuspage/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('preferences/', views.UserConfigView.as_view(), name='preferences'),
    path('password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('api-tokens/', views.TokenListView.as_view(), name='token_list'),
    path('api-tokens/add/', views.TokenEditView.as_view(), name='token_add'),
    path('api-tokens/<int:pk>/edit/', views.TokenEditView.as_view(), name='token_edit'),
    path('api-tokens/<int:pk>/delete/', views.TokenDeleteView.as_view(), name='token_delete'),
    path('twofactor/', views.TwoFactorListView.as_view(), name='device_list'),
    path('twofactor/add/', views.TwoFactorEditView.as_view(), name='device_add'),
    path('twofactor/<int:pk>/backup-codes/', views.TwoFactorBackupCodesListView.as_view(), name='device_backup_codes'),
    path('twofactor/<int:pk>/qr-code/', views.TwoFactorQRCodeListView.as_view(), name='device_qr_code'),
    path('twofactor/<int:pk>/edit/', views.TwoFactorEditView.as_view(), name='device_edit'),
    path('twofactor/<int:pk>/delete/', views.TwoFactorDeleteView.as_view(), name='device_delete'),
]

DevOps-finalproject/status-page/statuspage/templates/dashboard/home.html
{% extends 'base/dashboard.html' %}

{% block title %}
Dashboard
{% endblock %}

{% block dashboard_content %}
  <div>
    <dl class="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
      {% if perms.incidents.view_incident %}
      <div class="relative overflow-hidden rounded-lg bg-white dark:bg-zinc-800 px-4 pt-5 pb-12 shadow sm:px-6 sm:pt-6">
        <dt>
          <div class="absolute rounded-md bg-indigo-500 p-3 text-white">
            <!-- Heroicon name: outline/exclamation-triangle -->
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
            </svg>
          </div>
          <p class="ml-16 truncate text-sm font-medium text-gray-500">Open Incidents</p>
        </dt>
        <dd class="ml-16 flex items-baseline pb-6 sm:pb-7">
          <p class="text-2xl font-semibold text-gray-900 dark:text-gray-100">{{ open_incidents }}</p>
          <div class="absolute inset-x-0 bottom-0 bg-gray-50 dark:bg-zinc-900 px-4 py-4 sm:px-6">
            <div class="text-sm">
              <a href="{% url 'incidents:incident_list' %}" class="font-medium text-indigo-600 hover:text-indigo-500"> View all<span class="sr-only"> Total Open Incidents</span></a>
            </div>
          </div>
        </dd>
      </div>
      {% endif %}

      {% if perms.maintenances.view_maintenance %}
      <div class="relative overflow-hidden rounded-lg bg-white dark:bg-zinc-800 px-4 pt-5 pb-12 shadow sm:px-6 sm:pt-6">
        <dt>
          <div class="absolute rounded-md bg-indigo-500 p-3 text-white">
            <!-- Heroicon name: outline/wrench -->
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M21.75 6.75a4.5 4.5 0 01-4.884 4.484c-1.076-.091-2.264.071-2.95.904l-7.152 8.684a2.548 2.548 0 11-3.586-3.586l8.684-7.152c.833-.686.995-1.874.904-2.95a4.5 4.5 0 016.336-4.486l-3.276 3.276a3.004 3.004 0 002.25 2.25l3.276-3.276c.256.565.398 1.192.398 1.852z" />
              <path stroke-linecap="round" stroke-linejoin="round" d="M4.867 19.125h.008v.008h-.008v-.008z" />
            </svg>
          </div>
          <p class="ml-16 truncate text-sm font-medium text-gray-500">Open Maintenances</p>
        </dt>
        <dd class="ml-16 flex items-baseline pb-6 sm:pb-7">
          <p class="text-2xl font-semibold text-gray-900 dark:text-gray-100">{{ open_maintenances }}</p>
          <div class="absolute inset-x-0 bottom-0 bg-gray-50 dark:bg-zinc-900 px-4 py-4 sm:px-6">
            <div class="text-sm">
              <a href="{% url 'maintenances:maintenance_list' %}" class="font-medium text-indigo-600 hover:text-indigo-500"> View all<span class="sr-only"> Total Open Maintenances</span></a>
            </div>
          </div>
        </dd>
      </div>
      {% endif %}

      {% if perms.maintenances.view_maintenance %}
      <div class="relative overflow-hidden rounded-lg bg-white dark:bg-zinc-800 px-4 pt-5 pb-12 shadow sm:px-6 sm:pt-6">
        <dt>
          <div class="absolute rounded-md bg-indigo-500 p-3 text-white">
            <!-- Heroicon name: outline/clock -->
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <p class="ml-16 truncate text-sm font-medium text-gray-500">Upcoming Maintenances</p>
        </dt>
        <dd class="ml-16 flex items-baseline pb-6 sm:pb-7">
          <p class="text-2xl font-semibold text-gray-900 dark:text-gray-100">{{ upcoming_maintenances }}</p>
          <div class="absolute inset-x-0 bottom-0 bg-gray-50 dark:bg-zinc-900 px-4 py-4 sm:px-6">
            <div class="text-sm">
              <a href="{% url 'maintenances:maintenance_list' %}" class="font-medium text-indigo-600 hover:text-indigo-500"> View all<span class="sr-only"> Total Upcoming Maintenances</span></a>
            </div>
          </div>
        </dd>
      </div>
      {% endif %}
    </dl>
  </div>
{% endblock %}