DevOps-finalproject/status-page/statuspage/statuspage/urls.py
from django.conf import settings
from django.views.static import serve

from extras.plugins.urls import plugin_patterns, plugin_api_patterns, plugin_admin_patterns
from .admin import admin_site
from django.urls import path, include, re_path
from statuspage.views import HomeView, DashboardHomeView, SubscriberVerifyView, SubscriberManageView, \
    SubscriberUnsubscribeView, SubscriberSubscribeView, SubscriberRequestManagementKeyView
from users.views import LoginView, LogoutView
from statuspage.api.views import APIRootView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

openapi_info = openapi.Info(
    title="Status-Page API",
    default_version='v1',
    description="API to access Status-Page",
    terms_of_service="https://github.com/status-page/status-page",
    license=openapi.License(name="Apache 2.0 License"),
)

schema_view = get_schema_view(
    openapi_info,
    validators=['flex', 'ssv'],
    public=True,
    permission_classes=()
)

_patterns = [
    # Base Views
    path('', HomeView.as_view(), name='home'),

    path('subscribers/subscribe', SubscriberSubscribeView.as_view(), name='subscriber_subscribe'),
    path('subscribers/reqeust-management-key', SubscriberRequestManagementKeyView.as_view(), name='subscriber_management_key'),
    path('subscribers/<str:management_key>/verify', SubscriberVerifyView.as_view(), name='subscriber_verify'),
    path('subscribers/<str:management_key>/manage', SubscriberManageView.as_view(), name='subscriber_manage'),
    path('subscribers/<str:management_key>/unsubscribe', SubscriberUnsubscribeView.as_view(), name='subscriber_unsubscribe'),

    path('dashboard/', DashboardHomeView.as_view(), name='dashboard'),
    path('dashboard/login/', LoginView.as_view(), name='login'),
    path('dashboard/logout/', LogoutView.as_view(), name='logout'),

    # Apps
    path('dashboard/components/', include('components.urls')),
    path('dashboard/extras/', include('extras.urls')),
    path('dashboard/incidents/', include('incidents.urls')),
    path('dashboard/maintenances/', include('maintenances.urls')),
    path('dashboard/metrics/', include('metrics.urls')),
    path('dashboard/subscribers/', include('subscribers.urls')),
    path('dashboard/user/', include('users.urls')),

    # API
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/components/', include('components.api.urls')),
    path('api/extras/', include('extras.api.urls')),
    path('api/incidents/', include('incidents.api.urls')),
    path('api/maintenances/', include('maintenances.api.urls')),
    path('api/metrics/', include('metrics.api.urls')),
    path('api/subscribers/', include('subscribers.api.urls')),
    path('api/users/', include('users.api.urls')),
    path('api/docs/', schema_view.with_ui('swagger', cache_timeout=86400), name='api_docs'),
    path('api/redoc/', schema_view.with_ui('redoc', cache_timeout=86400), name='api_redocs'),
    re_path(r'^api/swagger(?P<format>.json|.yaml)$', schema_view.without_ui(cache_timeout=86400),
            name='schema_swagger'),

    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),

    # Plugins
    path('plugins/', include((plugin_patterns, 'plugins'))),
    path('api/plugins/', include((plugin_api_patterns, 'plugins-api'))),

    # Admin
    path('admin/background-tasks/', include('django_rq.urls')),
    path('admin/plugins/', include(plugin_admin_patterns)),
    path('admin/', admin_site.urls),

    path('__reload__/', include('django_browser_reload.urls')),
]

# Prepend BASE_PATH
urlpatterns = [
    path('{}'.format(settings.BASE_PATH), include(_patterns))
]

DevOps-finalproject/status-page/statuspage/users/api/urls.py
from django.urls import include, path

from statuspage.api.routers import StatusPageRouter
from . import views


router = StatusPageRouter()
router.APIRootView = views.UsersRootView

# Users and groups
router.register('users', views.UserViewSet)
router.register('groups', views.GroupViewSet)

# Tokens
router.register('tokens', views.TokenViewSet)

# Permissions
router.register('permissions', views.ObjectPermissionViewSet)

# User preferences
router.register('config', views.UserConfigViewSet, basename='userconfig')

app_name = 'users-api'
urlpatterns = [
    path('tokens/provision/', views.TokenProvisionView.as_view(), name='token_provision'),
    path('', include(router.urls)),
]

DevOps-finalproject/status-page/statuspage/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('preferences/', views.UserConfigView.as_view(), name='preferences'),
    path('password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('api-tokens/', views.TokenListView.as_view(), name='token_list'),
    path('api-tokens/add/', views.TokenEditView.as_view(), name='token_add'),
    path('api-tokens/<int:pk>/edit/', views.TokenEditView.as_view(), name='token_edit'),
    path('api-tokens/<int:pk>/delete/', views.TokenDeleteView.as_view(), name='token_delete'),
    path('twofactor/', views.TwoFactorListView.as_view(), name='device_list'),
    path('twofactor/add/', views.TwoFactorEditView.as_view(), name='device_add'),
    path('twofactor/<int:pk>/backup-codes/', views.TwoFactorBackupCodesListView.as_view(), name='device_backup_codes'),
    path('twofactor/<int:pk>/qr-code/', views.TwoFactorQRCodeListView.as_view(), name='device_qr_code'),
    path('twofactor/<int:pk>/edit/', views.TwoFactorEditView.as_view(), name='device_edit'),
    path('twofactor/<int:pk>/delete/', views.TwoFactorDeleteView.as_view(), name='device_delete'),
]

DevOps-finalproject/status-page/statuspage/users/admin/forms.py
from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth.models import User, Group
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import FieldError, ValidationError

from users.constants import CONSTRAINT_TOKEN_USER, OBJECTPERMISSION_OBJECT_TYPES
from users.models import ObjectPermission, Token
from utilities.forms.fields import ContentTypeMultipleChoiceField
from utilities.permissions import qs_filter_from_constraints

__all__ = (
    'GroupAdminForm',
    'TokenAdminForm',
    'ObjectPermissionForm',
)


class GroupAdminForm(forms.ModelForm):
    users = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(),
        required=False,
        widget=FilteredSelectMultiple('users', False)
    )

    class Meta:
        model = Group
        fields = ('name', 'users')

    def __init__(self, *args, **kwargs):
        super(GroupAdminForm, self).__init__(*args, **kwargs)

        if self.instance.pk:
            self.fields['users'].initial = self.instance.user_set.all()

    def save_m2m(self):
        self.instance.user_set.set(self.cleaned_data['users'])

    def save(self, *args, **kwargs):
        instance = super(GroupAdminForm, self).save()
        self.save_m2m()

        return instance


class TokenAdminForm(forms.ModelForm):
    key = forms.CharField(
        required=False,
        help_text="If no key is provided, one will be generated automatically."
    )

    class Meta:
        fields = [
            'user', 'key', 'write_enabled', 'expires', 'description', 'allowed_ips'
        ]
        model = Token


class ObjectPermissionForm(forms.ModelForm):
    object_types = ContentTypeMultipleChoiceField(
        queryset=ContentType.objects.all(),
        limit_choices_to=OBJECTPERMISSION_OBJECT_TYPES
    )
    can_view = forms.BooleanField(required=False)
    can_add = forms.BooleanField(required=False)
    can_change = forms.BooleanField(required=False)
    can_delete = forms.BooleanField(required=False)

    class Meta:
        model = ObjectPermission
        exclude = []
        help_texts = {
            'actions': 'Actions granted in addition to those listed above',
            'constraints': 'JSON expression of a queryset filter that will return only permitted objects. Leave null '
                           'to match all objects of this type. A list of multiple objects will result in a logical OR '
                           'operation.'
        }
        labels = {
            'actions': 'Additional actions'
        }
        widgets = {
            'constraints': forms.Textarea(attrs={'class': 'vLargeTextField'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Make the actions field optional since the admin form uses it only for non-CRUD actions
        self.fields['actions'].required = False

        # Order group and user fields
        self.fields['groups'].queryset = self.fields['groups'].queryset.order_by('name')
        self.fields['users'].queryset = self.fields['users'].queryset.order_by('username')

        # Check the appropriate checkboxes when editing an existing ObjectPermission
        if self.instance.pk:
            for action in ['view', 'add', 'change', 'delete']:
                if action in self.instance.actions:
                    self.fields[f'can_{action}'].initial = True
                    self.instance.actions.remove(action)

    def clean(self):
        super().clean()

        object_types = self.cleaned_data.get('object_types')
        constraints = self.cleaned_data.get('constraints')

        # Append any of the selected CRUD checkboxes to the actions list
        if not self.cleaned_data.get('actions'):
            self.cleaned_data['actions'] = list()
        for action in ['view', 'add', 'change', 'delete']:
            if self.cleaned_data[f'can_{action}'] and action not in self.cleaned_data['actions']:
                self.cleaned_data['actions'].append(action)

        # At least one action must be specified
        if not self.cleaned_data['actions']:
            raise ValidationError("At least one action must be selected.")

        # Validate the specified model constraints by attempting to execute a query. We don't care whether the query
        # returns anything; we just want to make sure the specified constraints are valid.
        if object_types and constraints:
            # Normalize the constraints to a list of dicts
            if type(constraints) is not list:
                constraints = [constraints]
            for ct in object_types:
                model = ct.model_class()
                try:
                    tokens = {
                        CONSTRAINT_TOKEN_USER: 0,  # Replace token with a null user ID
                    }
                    model.objects.filter(qs_filter_from_constraints(constraints, tokens)).exists()
                except FieldError as e:
                    raise ValidationError({
                        'constraints': f'Invalid filter for {model}: {e}'
                    })

DevOps-finalproject/status-page/statuspage/users/api/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.models import Group, User
from django.db.models import Count
from rest_framework.exceptions import AuthenticationFailed
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.routers import APIRootView
from rest_framework.status import HTTP_201_CREATED
from rest_framework.views import APIView
from rest_framework.viewsets import ViewSet

from statuspage.api.viewsets import StatusPageModelViewSet
from users import filtersets
from users.models import ObjectPermission, Token, UserConfig
from utilities.querysets import RestrictedQuerySet
from utilities.utils import deepmerge
from . import serializers


class UsersRootView(APIRootView):
    """
    Users API root view
    """
    def get_view_name(self):
        return 'Users'


#
# Users and groups
#

class UserViewSet(StatusPageModelViewSet):
    queryset = RestrictedQuerySet(model=User).prefetch_related('groups').order_by('username')
    serializer_class = serializers.UserSerializer
    filterset_class = filtersets.UserFilterSet


class GroupViewSet(StatusPageModelViewSet):
    queryset = RestrictedQuerySet(model=Group).annotate(user_count=Count('user')).order_by('name')
    serializer_class = serializers.GroupSerializer
    filterset_class = filtersets.GroupFilterSet


#
# REST API tokens
#

class TokenViewSet(StatusPageModelViewSet):
    queryset = RestrictedQuerySet(model=Token).prefetch_related('user')
    serializer_class = serializers.TokenSerializer
    filterset_class = filtersets.TokenFilterSet

    def get_queryset(self):
        """
        Limit the non-superusers to their own Tokens.
        """
        queryset = super().get_queryset()
        # Workaround for schema generation (drf_yasg)
        if getattr(self, 'swagger_fake_view', False):
            return queryset.none()
        if not self.request.user.is_authenticated:
            return queryset.none()
        if self.request.user.is_superuser:
            return queryset
        return queryset.filter(user=self.request.user)


class TokenProvisionView(APIView):
    """
    Non-authenticated REST API endpoint via which a user may create a Token.
    """
    permission_classes = []

    def post(self, request):
        serializer = serializers.TokenProvisionSerializer(data=request.data)
        serializer.is_valid()

        # Authenticate the user account based on the provided credentials
        username = serializer.data.get('username')
        password = serializer.data.get('password')
        if not username or not password:
            raise AuthenticationFailed("Username and password must be provided to provision a token.")
        user = authenticate(request=request, username=username, password=password)
        if user is None:
            raise AuthenticationFailed("Invalid username/password")

        # Create a new Token for the User
        token = Token(user=user)
        token.save()
        data = serializers.TokenSerializer(token, context={'request': request}).data

        return Response(data, status=HTTP_201_CREATED)


#
# ObjectPermissions
#

class ObjectPermissionViewSet(StatusPageModelViewSet):
    queryset = ObjectPermission.objects.prefetch_related('object_types', 'groups', 'users')
    serializer_class = serializers.ObjectPermissionSerializer
    filterset_class = filtersets.ObjectPermissionFilterSet


#
# User preferences
#

class UserConfigViewSet(ViewSet):
    """
    An API endpoint via which a user can update his or her own UserConfig data (but no one else's).
    """
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return UserConfig.objects.filter(user=self.request.user)

    def list(self, request):
        """
        Return the UserConfig for the currently authenticated User.
        """
        userconfig = self.get_queryset().first()

        return Response(userconfig.data)

    def patch(self, request):
        """
        Update the UserConfig for the currently authenticated User.
        """
        # TODO: How can we validate this data?
        userconfig = self.get_queryset().first()
        userconfig.data = deepmerge(userconfig.data, request.data)
        userconfig.save()

        return Response(userconfig.data)

DevOps-finalproject/status-page/statuspage/templates/users/api_tokens.html
{% extends 'base/dashboard.html' %}
{% load helpers %}
{% load render_table from django_tables2 %}
{% load buttons %}

{% block title %}
API Tokens
{% endblock %}

{% block controls %}
  {% add_button model %}
{% endblock %}

{% block dashboard_content %}
  {% render_table table 'inc/table.html' %}
  {% include 'inc/paginator.html' with paginator=table.paginator page=table.page rounded='md:rounded-b-lg' %}
{% endblock %}

DevOps-finalproject/status-page/statuspage/templates/users/password.html
{% extends 'base/dashboard.html' %}
{% load form_helpers %}

{% block title %}
Change Password
{% endblock %}

{% block dashboard_content %}
  <form method="post" action="" class="grow bg-zinc-100 dark:bg-zinc-800 p-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    {% csrf_token %}

    <div class="space-y-4">
      <div class="mb-4">
        <div class="text-2xl">Password</div>
      </div>
      <div class="mb-2">
        {% render_field form.old_password %}
      </div>
      <div class="mb-2">
        {% render_field form.new_password1 %}
      </div>
      <div class="mb-2">
        {% render_field form.new_password2 %}
      </div>
    </div>

    <div class="my-3 flex flex-row items-center justify-end space-x-2">
      <a class="border border-gray-500 hover:bg-gray-500 hover:text-white text-gray-500 px-2 py-1 rounded-md font-medium h-8 flex items-center" href="{% url 'users:profile' %}">Cancel</a>
      <button type="submit" name="_update" class="bg-green-500 hover:bg-green-400 text-white px-2 py-1 rounded-md font-medium h-8 flex items-center">Save</button>
    </div>
  </form>
{% endblock %}

DevOps-finalproject/status-page/statuspage/templates/users/preferences.html
{% extends 'base/dashboard.html' %}
{% load helpers %}
{% load form_helpers %}

{% block title %}
User Preferences
{% endblock %}

{% block dashboard_content %}
  <form method="post" action="" id="preferences-update" class="grow bg-zinc-100 dark:bg-zinc-800 p-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    {% csrf_token %}

    {# Built-in preferences #}
    <div class="space-y-4">
      {% for group, fields in form.fieldsets %}
        <div>
          <div class="mb-4">
            <div class="text-2xl">{{ group }}</div>
          </div>
          {% for name in fields %}
            <div class="mb-2">
              {% render_field form|getfield:name %}
            </div>
          {% endfor %}
        </div>
      {% endfor %}
    </div>

    {# Plugin preferences #}
    <div class="space-y-4">
      {% with plugin_fields=form.plugin_fields %}
        {% if plugin_fields %}
          <div>
            <div class="mb-4">
              <h5 class="text-2xl">Plugins</h5>
            </div>
            {% for name in plugin_fields %}
              <div class="mb-2">
                {% render_field form|getfield:name %}
              </div>
            {% endfor %}
          </div>
        {% endif %}
      {% endwith %}
    </div>

    {# Table configurations #}
    <div>
      <div class="mb-4">
        <div class="text-2xl">Table Configurations</div>
      </div>
      <div>
        {% if request.user.config.data.tables %}
          <label class="col-sm-3 col-form-label text-lg">
            Clear table preferences
          </label>
          <div>
            <table class="text-left w-full object-list divide-y divide-gray-400 dark:divide-gray-400">
              <thead>
                <tr>
                  <th>
                    <input type="checkbox" class="toggle h-4 w-4 rounded border-gray-300 text-indigo-600" title="Toggle All">
                  </th>
                  <th>Table</th>
                  <th>Ordering</th>
                  <th>Columns</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
                {% for table, prefs in request.user.config.data.tables.items %}
                  <tr class="py-1">
                    <td>
                      <input type="checkbox" name="pk" value="tables.{{ table }}" class="h-4 w-4 rounded border-gray-300 text-indigo-600" />
                    </td>
                    <td>{{ table }}</td>
                    <td>{{ prefs.ordering|join:", "|placeholder }}</td>
                    <td>{{ prefs.columns|join:", "|placeholder }}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        {% else %}
          <div>
            <p class="text-gray-500 dark:text-gray-400">None found</p>
          </div>
        {% endif %}
      </div>
    </div>

    <div class="my-3 flex flex-row items-center justify-end space-x-2">
      <a class="border border-gray-500 hover:bg-gray-500 hover:text-white text-gray-500 px-2 py-1 rounded-md font-medium h-8 flex items-center" href="{% url 'users:profile' %}">Cancel</a>
      <button type="submit" name="_update" class="bg-green-500 hover:bg-green-400 text-white px-2 py-1 rounded-md font-medium h-8 flex items-center">Save</button>
    </div>
  </form>
{% endblock %}

DevOps-finalproject/status-page/statuspage/templates/users/profile.html
{% extends 'base/dashboard.html' %}
{% load helpers %}
{% load render_table from django_tables2 %}

{% block title %}
User Profile
{% endblock %}

{% block dashboard_content %}
  <div class="flex flex-col space-y-4">
    <div class="flex flex-row space-x-4">
      <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
        <div class="text-2xl">Account Details</div>
        <div class="px-4">
          <table class="text-left w-full">
            <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
              <tr>
                <th scope="row" class="pr-6 py-1">Username</th>
                <td>{{ request.user.username }}</td>
              </tr>
              <tr>
                <th scope="row" class="pr-6 py-1">Full Name</th>
                <td>
                  {% if request.user.first_name or request.user.last_name %}
                    {{ request.user.first_name }} {{ request.user.last_name }}
                  {% else %}
                    {{ ''|placeholder }}
                  {% endif %}
                </td>
              </tr>
              <tr>
                <th scope="row" class="pr-6 py-1">Email</th>
                <td>{{ request.user.email|placeholder }}</td>
              </tr>
              <tr>
                <th scope="row" class="pr-6 py-1">Account Created</th>
                <td>{{ request.user.date_joined|annotated_date }}</td>
              </tr>
              <tr>
                <th scope="row" class="pr-6 py-1">Superuser</th>
                <td>{% checkmark request.user.is_superuser %}</td>
              </tr>
              <tr>
                <th scope="row" class="pr-6 py-1">Admin Access</th>
                <td>{% checkmark request.user.is_staff %}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
        <div class="text-2xl">Assigned Groups</div>
        <div class="px-4">
          <ul class="divide-y divide-gray-200 dark:divide-gray-700">
            {% for group in request.user.groups.all %}
              <li class="py-1">{{ group }}</li>
            {% empty %}
              <li class="py-1">None</li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
    {% if perms.extras.view_objectchange %}
      <div class="bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
        <div class="text-2xl text-center">Recent Activity</div>
        <div>
          {% render_table changelog_table 'inc/table.html' %}
        </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

DevOps-finalproject/status-page/statuspage/templates/users/two_factor.html
{% extends 'base/dashboard.html' %}
{% load helpers %}
{% load render_table from django_tables2 %}
{% load buttons %}
{% load form_helpers %}

{% block title %}
Two Factor Devices
{% endblock %}

{% block controls %}
  <div class="flex flex-row">
    <form action="{% url 'users:device_add' %}" method="get" class="flex flex-row items-end space-x-1">
      {% render_form form %}
      <button class="bg-green-500 hover:bg-green-400 text-white px-2 py-2 rounded-md font-medium" type="submit">
        <i class="mdi mdi-plus-thick"></i> Add
      </button>
    </form>
    {% if show_generate_backup_codes %}
      <form action="{% url 'users:device_list' %}" method="post" class="flex flex-row items-end space-x-1">
        {% csrf_token %}
        <input type="hidden" name="action" value="generate_backup_codes">
        <button class="bg-green-500 hover:bg-green-400 text-white px-2 py-2 rounded-md font-medium" type="submit">
          Generate Backup Codes
        </button>
      </form>
    {% endif %}
  </div>
{% endblock %}

{% block dashboard_content %}
  {% render_table table 'inc/table.html' %}
  {% include 'inc/paginator.html' with paginator=table.paginator page=table.page rounded='md:rounded-b-lg' %}
{% endblock %}

DevOps-finalproject/status-page/statuspage/templates/users/two_factor_backup_codes.html
{% extends 'base/dashboard.html' %}
{% load helpers %}
{% load render_table from django_tables2 %}
{% load buttons %}

{% block title %}
View Backup Codes
{% endblock %}

{% block controls %}
  <a href="{% url 'users:device_list' %}" class="bg-blue-500 hover:bg-blue-400 text-white px-2 py-2 rounded-md font-medium" type="button">
    Go back
  </a>
{% endblock %}

{% block dashboard_content %}
  <div class="flex flex-col bg-zinc-200 dark:bg-zinc-800 rounded-md px-2 py-2 space-y-4">
    <div class="text-2xl">Recovery Codes</div>
    <div>Store these recovery codes in a secure password manager.<br>They can be used to recover access to your account if your two factor authentication device is lost.</div>
    <div class="flex flex-row space-y-2">
      <div class="grid grid-cols-2 gap-4">
        {% for code in backup_codes %}
          <div class="bg-zinc-300 dark:bg-zinc-900 rounded-md font-[monospace] px-2 py-2 text-lg">{{ code.token }}</div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

DevOps-finalproject/status-page/statuspage/templates/users/two_factor_qr_code.html
{% extends 'base/dashboard.html' %}
{% load helpers %}
{% load render_table from django_tables2 %}
{% load buttons %}

{% block title %}
View QR Code
{% endblock %}

{% block controls %}
  <a href="{% url 'users:device_list' %}" class="bg-blue-500 hover:bg-blue-400 text-white px-2 py-2 rounded-md font-medium" type="button">
    Go back
  </a>
{% endblock %}

{% block dashboard_content %}
<div class="flex flex-col space-y-2 items-center">
  <div class="text-2xl">Two Factor QR Code</div>
  <div class="text-black bg-white w-64 h-64">{{ qr_code }}</div>
  <div class="bg-zinc-300 dark:bg-zinc-900 rounded-md font-[monospace] px-2 py-2 text-lg">{{ config_url }}</div>
  <div class="pt-8">
    <form action="" method="post" class="flex flex-row space-x-2 items-center">
      {% csrf_token %}
      <input type="text" name="token" autocomplete="two-factor" placeholder="Enter Two Factor Code" class="rounded-md border-gray-300 shadow-sm text-black dark:text-white dark:bg-zinc-900 dark:border-zinc-700">
      <button class="bg-blue-500 hover:bg-blue-400 text-white px-2 py-2 rounded-md font-medium" type="submit">
        Verify
      </button>
    </form>
  </div>
</div>
{% endblock %}